services:
  - type: web
    name: formula-predictions-backend
    runtime: python
    plan: free
    autoDeploy: false
    region: frankfurt
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: sh -c "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"

  - type: web
    name: formula-predictions-frontend
    runtime: static
    autoDeploy: false
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    buildFilter:
      paths:
        - src/**/*.ts
        - src/**/*.tsx
      ignoredPaths:
        - src/**/*.test.ts
        - src/**/*.test.tsx
    envVars:
      - key: VITE_API_URL
        value: "https://formula-predictions-backend.onrender.com"
